"""PDF Generation Service for RFCO Documents"""
import logging
from weasyprint import HTML, CSS
from jinja2 import Environment, FileSystemLoader
from pathlib import Path
from decimal import Decimal
from datetime import date, datetime
from typing import Optional

from app.core.config import settings

logger = logging.getLogger(__name__)


class PDFGenerator:
    """Generate PDF documents for RFCOs"""

    def __init__(self):
        template_dir = Path(__file__).parent.parent / "templates"

        # Ensure template directory exists
        if not template_dir.exists():
            logger.warning(f"Templates directory does not exist: {template_dir}")
            template_dir.mkdir(parents=True, exist_ok=True)

        self.template_dir = template_dir
        self.env = Environment(loader=FileSystemLoader(str(template_dir)))

        # Custom filters
        self.env.filters['currency'] = self._currency_filter
        self.env.filters['date'] = self._date_filter

        logger.info(f"PDFGenerator initialized with template dir: {template_dir}")

    @staticmethod
    def _currency_filter(value: Decimal | float | int | None) -> str:
        """Format as currency"""
        if value is None:
            return "$0.00"
        return f"${float(value):,.2f}"

    @staticmethod
    def _date_filter(value: date | str | datetime | None) -> str:
        """Format date"""
        if value is None:
            return ""
        if isinstance(value, str):
            try:
                value = datetime.fromisoformat(value.replace('Z', '+00:00')).date()
            except ValueError:
                return value
        if isinstance(value, datetime):
            value = value.date()
        return value.strftime("%B %d, %Y")

    def generate_rfco_pdf(
        self,
        tnm_ticket: dict,
        project: dict,
        output_path: Optional[str] = None,
        settings: Optional[dict] = None,
    ) -> bytes:
        """
        Generate RFCO PDF

        Args:
            tnm_ticket: TNM ticket data (dict)
            project: Project data (dict)
            output_path: Optional file path to save PDF
            settings: Optional database settings dict (overrides config defaults)

        Returns:
            bytes: PDF content

        Raises:
            ValueError: If required data is missing
            RuntimeError: If PDF generation fails
        """
        try:
            # Validate required fields
            if not tnm_ticket:
                raise ValueError("TNM ticket data is required")
            if not project:
                raise ValueError("Project data is required")

            required_ticket_fields = ['tnm_number', 'title', 'proposal_amount']
            for field in required_ticket_fields:
                if field not in tnm_ticket:
                    raise ValueError(f"Missing required ticket field: {field}")

            required_project_fields = ['name', 'project_number']
            for field in required_project_fields:
                if field not in project:
                    raise ValueError(f"Missing required project field: {field}")

            logger.info(f"Generating PDF for TNM ticket: {tnm_ticket.get('tnm_number')}")

            # Use database settings if provided, otherwise fallback to config defaults
            if settings is None:
                settings = {}

            # Import config settings at runtime to avoid circular imports
            from app.core.config import settings as config_settings

            # Company settings
            company_name = settings.get('COMPANY_NAME', config_settings.COMPANY_NAME)
            company_email = settings.get('COMPANY_EMAIL', config_settings.COMPANY_EMAIL)
            company_phone = settings.get('COMPANY_PHONE', config_settings.COMPANY_PHONE)

            # PDF customization settings
            pdf_header_show_company_info = settings.get('PDF_HEADER_SHOW_COMPANY_INFO', True)
            pdf_document_title = settings.get('PDF_DOCUMENT_TITLE', 'REQUEST FOR CHANGE ORDER (RFCO)')
            pdf_primary_color = settings.get('PDF_PRIMARY_COLOR', '#1d4ed8')
            pdf_show_project_info_section = settings.get('PDF_SHOW_PROJECT_INFO_SECTION', True)
            pdf_show_notes_section = settings.get('PDF_SHOW_NOTES_SECTION', True)
            pdf_show_signature_section = settings.get('PDF_SHOW_SIGNATURE_SECTION', True)
            pdf_signature_title = settings.get('PDF_SIGNATURE_TITLE', 'General Contractor Approval:')
            pdf_footer_text = settings.get('PDF_FOOTER_TEXT', 'This document was generated by {company_name}')
            show_company_info_in_footer = settings.get('PDF_SHOW_COMPANY_INFO_IN_FOOTER', True)

            # Due date settings
            pdf_show_due_date = settings.get('PDF_SHOW_DUE_DATE', True)
            pdf_due_date_label = settings.get('PDF_DUE_DATE_LABEL', 'Response Due Date:')

            # Format footer text with variables
            footer_text = pdf_footer_text.format(
                company_name=company_name,
                company_email=company_email,
                company_phone=company_phone
            )

            # Render HTML template
            template = self.env.get_template('rfco_pdf.html')

            # Add current date/time for footer
            now = datetime.now()

            html_content = template.render(
                company_name=company_name,
                company_email=company_email,
                company_phone=company_phone,
                pdf_header_show_company_info=pdf_header_show_company_info,
                pdf_document_title=pdf_document_title,
                pdf_primary_color=pdf_primary_color,
                pdf_show_project_info_section=pdf_show_project_info_section,
                pdf_show_notes_section=pdf_show_notes_section,
                pdf_show_signature_section=pdf_show_signature_section,
                pdf_signature_title=pdf_signature_title,
                pdf_footer_text=footer_text,
                show_company_info_in_footer=show_company_info_in_footer,
                pdf_show_due_date=pdf_show_due_date,
                pdf_due_date_label=pdf_due_date_label,
                tnm_ticket=tnm_ticket,
                project=project,
                now=now,
            )

            logger.debug(f"Rendered HTML template, length: {len(html_content)} chars")

            # Generate PDF
            pdf = HTML(string=html_content).write_pdf()

            logger.info(f"PDF generated successfully, size: {len(pdf)} bytes")

            # Optionally save to file
            if output_path:
                output_file = Path(output_path)
                output_file.parent.mkdir(parents=True, exist_ok=True)
                with open(output_path, 'wb') as f:
                    f.write(pdf)
                logger.info(f"PDF saved to: {output_path}")

            return pdf

        except Exception as e:
            logger.error(f"Error generating PDF: {str(e)}", exc_info=True)
            raise RuntimeError(f"Failed to generate PDF: {str(e)}") from e


# Singleton instance
pdf_generator = PDFGenerator()
