#!/usr/bin/env python3
"""Add missing PDF settings to database"""
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from sqlalchemy import select
import os

# Add app to path
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent / "app"))

from app.models.app_settings import AppSettings
from app.core.config import settings

async def add_pdf_settings():
    """Add PDF-related settings if they don't exist"""

    # Create engine
    engine = create_async_engine(
        settings.DATABASE_URL,
        echo=False,
    )

    AsyncSessionLocal = async_sessionmaker(
        engine,
        expire_on_commit=False,
        autocommit=False,
        autoflush=False,
    )

    async with AsyncSessionLocal() as db:
        # Define new PDF settings
        new_settings = [
            {
                "key": "PDF_FOOTER_TEXT",
                "value": "This document was generated by {company_name}",
                "category": "pdf",
                "data_type": "string",
                "description": "Footer text for PDF documents (variables: {company_name}, {company_email}, {company_phone})"
            },
            {
                "key": "PDF_SHOW_COMPANY_INFO_IN_FOOTER",
                "value": "true",
                "category": "pdf",
                "data_type": "boolean",
                "description": "Show company name and email in PDF footer"
            },
        ]

        added = 0
        for setting_data in new_settings:
            # Check if setting already exists
            result = await db.execute(
                select(AppSettings).where(AppSettings.key == setting_data['key'])
            )
            existing = result.scalar_one_or_none()

            if not existing:
                setting = AppSettings(**setting_data)
                db.add(setting)
                added += 1
                print(f"✓ Added setting: {setting_data['key']}")
            else:
                print(f"  Setting already exists: {setting_data['key']}")

        if added > 0:
            await db.commit()
            print(f"\n✅ Added {added} new PDF settings")
        else:
            print("\n✅ All PDF settings already exist")

    await engine.dispose()

if __name__ == '__main__':
    asyncio.run(add_pdf_settings())
